-- 보호자
CREATE TABLE TBL_PERSON (
	PERSON_ID NUMBER,
	PERSON_NAME VARCHAR2(100) NOT NULL,
	PERSON_ADDRESS VARCHAR2(100) NOT NULL,
	PERSON_PHONE VARCHAR2(100) NOT NULL UNIQUE,
	PERSON_EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	CONSTRAINT PK_PERSON PRIMARY KEY (PERSON_ID)
);

-- 종
CREATE TABLE TBL_SPECIES (
	SPECIES_ID NUMBER,
	SPECIES_NAME VARCHAR2(100) NOT NULL UNIQUE,
	CONSTRAINT PK_SPECIES PRIMARY KEY (SPECIES_ID)
);

-- 품종
CREATE TABLE TBL_TYPE (
	TYPE_ID NUMBER,
	TYPE_NAME VARCHAR2(100) NOT NULL UNIQUE,
	SPECIES_ID NUMBER,
	CONSTRAINT PK_TYPE PRIMARY KEY (TYPE_ID),
	CONSTRAINT FK_TYPE FOREIGN KEY (SPECIES_ID)
		REFERENCES TBL_SPECIES(SPECIES_ID)
);

-- 반려동물
CREATE TABLE TBL_ANIMAL (
	ANIMAL_ID NUMBER,
	ANIMAL_NAME VARCHAR2(100) NOT NULL,
	ANIMAL_GENDER CHAR(1) NOT NULL
		CONSTRAINT CHECK_GEN CHECK(ANIMAL_GENDER = 'M' OR ANIMAL_GENDER = 'F'),
	ANIMAL_AGE NUMBER NOT NULL,
	PERSON_ID NUMBER NOT NULL,
	TYPE_ID NUMBER NOT NULL,
	CONSTRAINT PK_ANIMAL PRIMARY KEY (ANIMAL_ID),
	CONSTRAINT FK_ANIMAL_PERSON FOREIGN KEY (PERSON_ID)
		REFERENCES TBL_PERSON(PERSON_ID),
	CONSTRAINT FK_ANIMAL_TYPE FOREIGN KEY (TYPE_ID)
		REFERENCES TBL_TYPE(TYPE_ID)
);

-- 각 테이블의 시퀀스 생성
CREATE SEQUENCE SEQ_PERSON;
CREATE SEQUENCE SEQ_SPECIES;
CREATE SEQUENCE SEQ_TYPE;
CREATE SEQUENCE SEQ_ANIMAL;

INSERT INTO TBL_PERSON
--VALUES (SEQ_PERSON.NEXTVAL, '나미리', '서울시 강남구', '010-1234-5678', 'a@naver.com');
--VALUES (SEQ_PERSON.NEXTVAL, '채성아', '서울시 강동구', '010-1234-1234', 'b@naver.com');
VALUES (SEQ_PERSON.NEXTVAL, '흑곰', '서울시 강서구', '010-8765-4321', 'c@naver.com');

INSERT INTO TBL_SPECIES
--VALUES (SEQ_SPECIES.NEXTVAL, '개');
VALUES (SEQ_SPECIES.NEXTVAL, '고양이');

INSERT INTO TBL_TYPE
--VALUES (SEQ_TYPE.NEXTVAL, '말티즈', 1);
--VALUES (SEQ_TYPE.NEXTVAL, '시츄', 1);
--VALUES (SEQ_TYPE.NEXTVAL, '도베르만', 1);
--VALUES (SEQ_TYPE.NEXTVAL, '페르시안 블루', 2);
VALUES (SEQ_TYPE.NEXTVAL, '코숏', 2);

INSERT INTO TBL_ANIMAL
--VALUES (SEQ_ANIMAL.NEXTVAL, '가루', 'M', 4, 1, 1);
--VALUES (SEQ_ANIMAL.NEXTVAL, '소라', 'F', 6, 2, 4);
VALUES (SEQ_ANIMAL.NEXTVAL, '콩이', 'F', 1, 3, 2);

SELECT * FROM TBL_PERSON;
SELECT * FROM TBL_SPECIES;
SELECT * FROM TBL_TYPE;
SELECT * FROM TBL_ANIMAL;