-- 1. JOIN - INNER

-- 도서테이블과 도서가격 테이블 생성
CREATE TABLE TBL_BOOKS(
	BOOK_ID NUMBER,
	BOOK_TITLE VARCHAR2(1000),
	BOOK_AUTHOR VARCHAR2(100),
	CONSTRAINT PK_BOOK PRIMARY KEY (BOOK_ID)
);

CREATE TABLE TBL_BOOKPRICE(
	BP_ID NUMBER,
	BP_PRICE NUMBER,
	CONSTRAINT BP_PK PRIMARY KEY(BP_ID)
);

INSERT INTO TBL_BOOKS
--VALUES(1, '위대한 개츠비', 'F.스콧 피츠제럴드');
--VALUES(2, '해리포터와 마법사의 돌', 'J.K 롤링');
--VALUES(3, '1984', ' 조지오웰');
--VALUES(4, '오만과 편견', '제인 오스틴');
--VALUES(5, '데미안', '헤르만 헤세');
--VALUES(6, '모모', '미하엘 엔더');
VALUES(7, 'DBMS 완전정복', 'DBMS');

INSERT INTO TBL_BOOKPRICE
--VALUES(1, 15000);
--VALUES(2, 18000);
--VALUES(3, 14000);
--VALUES(4, 17000);
--VALUES(5, 18000);
--VALUES(6, 20000);
VALUES(7, 20000);

-- 2개의 테이블 내부조인
SELECT A.BOOK_ID, A.BOOK_TITLE, A.BOOK_AUTHOR, B.BP_ID, B.BP_PRICE
FROM TBL_BOOKS A INNER JOIN TBL_BOOKPRICE B
ON A.BOOK_ID = B.BP_ID;

DROP TABLE TBL_BOOKS;
DROP TABLE TBL_BOOKPRICE;
-- 도서관
-- 도서 테이블, 회원 테이블, 렌탈 테이블
CREATE TABLE TBL_BOOKS(
	BOOK_ID NUMBER,
	BOOK_TITLE VARCHAR2(1000),
	BOOK_AUTHOR VARCHAR2(100),
	CONSTRAINT PK_BOOK PRIMARY KEY (BOOK_ID)
);

CREATE TABLE TBL_MEMBER(
	MEM_ID NUMBER,
	MEM_NAME VARCHAR2(100),
	MEM_PHONE VARCHAR2(100),
	MEM_EMAIL VARCHAR2(100),
	CONSTRAINT PK_MEMBER PRIMARY KEY (MEM_ID)
);

CREATE TABLE TBL_RENTAL(
	REN_ID NUMBER,
	MEM_ID NUMBER,
	BOOK_ID NUMBER,
	REN_RENTALDATE DATE,
	REN_RETURNDATE DATE,
	CONSTRAINT PK_RENTAL PRIMARY KEY (REN_ID),
	CONSTRAINT FK_RENTAL_MEM FOREIGN KEY (MEM_ID) REFERENCES TBL_MEMBER(MEM_ID),
	CONSTRAINT FK_RENTAL_BOOKS FOREIGN KEY (BOOK_ID) REFERENCES TBL_BOOKS(BOOK_ID)
);

INSERT INTO TBL_BOOKS
--VALUES(1, '위대한 개츠비', 'F.스콧 피츠제럴드');
--VALUES(2, '해리포터와 마법사의 돌', 'J.K 롤링');
--VALUES(3, '1984', '조지오웰');
--VALUES(4, '오만과 편견', '제인 오스틴');
--VALUES(5, '데미안', '헤르만 헤세');
--VALUES(6, '모모', '미하엘 엔더');
--VALUES(7, 'DBMS 완전정복', 'DBMS');

INSERT INTO TBL_MEMBER
VALUES
--(1, '짱구', '123-456-7890', 'aaa@koreait.com');
--(2, '유리', '987-654-3210', 'bbb@koreait.com');
--(3, '철수', '555-123-4567', 'ccc@koreait.com');
--(4, '훈이', '777-888-9999', 'ddd@koreait.com');
--(5, '맹구', '555-777-3333', 'eee@koreait.com');

INSERT INTO TBL_RENTAL
VALUES
--(1, 1, 3, TO_DATE('2023-12-11', 'YYYY-MM-DD'), TO_DATE('2023-12-18', 'YYYY-MM-DD'));
--(2, 2, 1, TO_DATE('2023-12-11', 'YYYY-MM-DD'), TO_DATE('2023-12-18', 'YYYY-MM-DD'));
--(3, 3, 2, TO_DATE('2023-12-13', 'YYYY-MM-DD'), TO_DATE('2023-12-20', 'YYYY-MM-DD'));
--(4, 4, 4, TO_DATE('2023-12-20', 'YYYY-MM-DD'), TO_DATE('2023-12-27', 'YYYY-MM-DD'));
--(5, 5, 5, TO_DATE('2023-12-22', 'YYYY-MM-DD'), TO_DATE('2023-12-29', 'YYYY-MM-DD'));

-- 등가조인 : 두 개 이상의 테이블 조인시,특정 컬럼들의 값이 서로 같은 행만 결과로 반환

-- 대여 정보의 책의 저자를 가져오는 등가조인
-- 1) 행의 개수 먼저 파악 후 선행, 후행 테이블 설정
SELECT COUNT(*)
FROM TBL_BOOKS;

SELECT COUNT(*)
FROM TBL_RENTAL;

-- 2) JOIN을 사용하여 두개의 테이블 조회
SELECT TR.REN_RENTALDATE, TR.REN_RETURNDATE, TB.BOOK_AUTHOR
FROM TBL_RENTAL tr INNER JOIN TBL_BOOKS tb
-- 두개의 테이블에서 일치하는 컬럼 확인 후 ON절에 추가
ON TR.BOOK_ID = TB.BOOK_ID;

-- 대여한 책이름과 반납날짜 가져오는 등가조인
SELECT TB.BOOK_TITLE, TR.REN_RETURNDATE
FROM TBL_BOOKS tb JOIN TBL_RENTAL tr 
ON TB.BOOK_ID = TR.BOOK_ID;

--SELECT TB.* , TR.*
SELECT *
FROM TBL_BOOKS tb JOIN TBL_RENTAL tr 
ON TB.BOOK_ID = TR.BOOK_ID;

-- 회원의 이름과 대여한 책의 제목만 가져오는 등가조인
-- > TBL_BOOKS과 TBL_MEMBER가 동일한 컬럼이 없는 경우
SELECT TB.BOOK_TITLE, TM.MEM_NAME
FROM TBL_RENTAL TR	-- 선행테이블
JOIN TBL_MEMBER TM ON TR.MEM_ID = TM.MEM_ID		-- 후행 테이블
JOIN TBL_BOOKS TB ON TR.MEM_ID = TB.BOOK_ID;	-- 후행 테이블

-- 비등가조인 : 두 테이블가느이 조건이 같음이 아닌 범위 조건 등을 사용하는 방식

-- 책 대여일 ~ 반납일 사이에 특정 날짜가 포함되어있는지 조회
SELECT TM.MEM_NAME, TB.BOOK_TITLE, TR.REN_RENTALDATE, TR.REN_RETURNDATE
FROM TBL_RENTAL TR
JOIN TBL_BOOKS TB ON TR.BOOK_ID = TB.BOOK_ID
JOIN TBL_MEMBER TM ON TR.MEM_ID = TM.MEM_ID
WHERE TO_DATE('2023-12-25', 'YYYY-MM-DD')
	BETWEEN TR.REN_RENTALDATE AND TR.REN_RETURNDATE;

-- 대여 기간에 따라 책의 대여 상태 확인
-- 7일 이하 단기 대여, 7일 이상 장기 대여
SELECT TB.BOOK_TITLE, TM.MEM_NAME, TR.REN_RENTALDATE, TR.REN_RETURNDATE,
	CASE
		WHEN TR.REN_RETURNDATE - TR.REN_RENTALDATE <= 7 THEN '단기대여'
		ELSE '장기대여'
	END AS RENTAL_TYPE
FROM TBL_RENTAL TR
JOIN TBL_BOOKS TB ON TR.BOOK_ID = TB.BOOK_ID
JOIN TBL_MEMBER TM ON TR.MEM_ID = TM.MEM_ID;
	
-- 실행순서 :  FROM → ON → JOIN → WHERE → GROUP BY → HAVING → SELECT → ORDER BY
-- FROM : 테이블의 뷰나 데이터 가져오기
-- ON : JOIN절의 조건 평가
-- JOIN : 지정된 조건에 따라 두 개 이상의 컬럼 사용
-- WHERE : 조인 결과에서 조건에 맞는 행 필터링
-- GROUP BY : 데이터 그룹화 (집계함수와 주로 사용)
-- HAVING : GROUP BY로 그룹화된 데이터에 대해 조건 작성
-- SELECT : 조회할 컬럼을 선택(집계함수, 별칭)
-- ORDER BY : 최종 결과 정렬 (ASC, DESC)
-- ** ON절과 WHERE절을 나눠서 작성했을 떄 결과가 같다면 ON절로만 작성하기

CREATE TABLE TBL_BOOKPRICE(
	BP_ID NUMBER,
	BP_PRICE NUMBER,
	CONSTRAINT BP_PK PRIMARY KEY(BP_ID)
);

INSERT INTO TBL_BOOKPRICE
--VALUES(1, 15000);
--VALUES(2, 18000);
--VALUES(3, 14000);
--VALUES(4, 17000);

-- 1) 왼쪽 외부조인 (LEFT OUTER JOIN)
-- BOOKS 테이블 기준 왼쪽 외부조인을 수행하고 BOOKSPRICE 테이블의 데이터 포함
-- (왼쪽 테이블의 데이터가 없어도 결과에 포함)
SELECT TB.BOOK_ID, TB.BOOK_TITLE, TB.BOOK_AUTHOR, TP.BP_ID, TP.BP_PRICE
FROM TBL_BOOKS TB
LEFT OUTER JOIN TBL_BOOKPRICE TP
ON TB.BOOK_ID = TP.BP_ID;

-- 2) 오른쪽 외부조인 (RIGHT OUTER JOIN)
-- BOOKS 테이블 기준 오른쪽 외부조인을 수행하고 BOOKSPRICE 테이블의 데이터 포함
-- (오른쪽 테이블의 데이터가 없어도 결과에 포함)
SELECT TB.BOOK_ID, TB.BOOK_TITLE, TB.BOOK_AUTHOR, TP.BP_ID, TP.BP_PRICE
FROM TBL_BOOKS TB
RIGHT OUTER JOIN TBL_BOOKPRICE TP
ON TB.BOOK_ID = TP.BP_ID;

INSERT INTO TBL_BOOKS tb
VALUES(10, 'DBMS', 'DB');
INSERT INTO TBL_BOOKPRICE
--VALUES(5, 20000);
--VALUES(6, 16000);
VALUES(7, 20000);
SELECT * FROM TBL_BOOKPRICE;

-- 3) 완전 외부조인 (FULL OUTER JOIN)
-- 왼쪽 테이블과 오른쪽 테이블의 데이터를 모두 포함
-- 어느 한쪽에만 데이터가 있는 경우에도 결과에 포함
SELECT TB.BOOK_ID, TB.BOOK_TITLE, TB.BOOK_AUTHOR, TP.BP_ID, TP.BP_PRICE
FROM TBL_BOOKS TB
FULL OUTER JOIN TBL_BOOKPRICE TP
ON TB.BOOK_ID = TP.BP_ID;

SELECT * FROM TBL_BOOKPRICE;
SELECT * FROM TBL_BOOKS;
SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_RENTAL;

